<?xml version="1.0" encoding="utf-8"?><Database Name="hot79334_aha_shine" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=__DB_HOST__;Initial Catalog=__DB_NAME__;Persist Security Info=True;User ID=__DB_USER__" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aka48637_abcConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bspa_bophan_table" Member="bspa_bophan_tables">
    <Type Name="bspa_bophan_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenbophan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.web_post_table" Member="web_post_tables">
    <Type Name="web_post_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_category" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="name_en" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="content_post" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="noibat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="phanloai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="giaban_sanpham" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="phantram_chotsale_sanpham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong_ton_sanpham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hsd_sanpham" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="giavon_sanpham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="giaban_dichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="phantram_lamdichvu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phantram_chotsale_dichvu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thoiluong_dichvu_phut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donvitinh_sp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hienthi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_nganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_caidatchung_table" Member="bspa_caidatchung_tables">
    <Type Name="bspa_caidatchung_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="chitieu_doanhso_dichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="chitieu_doanhso_mypham" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_chamcong_table" Member="bspa_chamcong_tables">
    <Type Name="bspa_chamcong_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="chamcong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_chiphi_codinh_table" Member="bspa_chiphi_codinh_tables">
    <Type Name="bspa_chiphi_codinh_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tenchiphi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="apdung" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_data_khachhang_table" Member="bspa_data_khachhang_tables">
    <Type Name="bspa_data_khachhang_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tenkhachhang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="anhdaidien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="magioithieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nguoichamsoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nhomkhachhang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sodiem_e_aha" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="vnd_tu_e_aha" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="capbac" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="solan_lencap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_datlich_table" Member="bspa_datlich_tables">
    <Type Name="bspa_datlich_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenkhachhang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaydat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dichvu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tendichvu_taithoidiemnay" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nhanvien_thuchien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="trangthai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguongoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thoiluong_dichvu_phut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayketthucdukien" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_hinhanhthuchi_table" Member="bspa_hinhanhthuchi_tables">
    <Type Name="bspa_hinhanhthuchi_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_thuchi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_hoadon_chitiet_table" Member="bspa_hoadon_chitiet_tables">
    <Type Name="bspa_hoadon_chitiet_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_hoadon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_dvsp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_dvsp_taithoidiemnay" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_dvsp_taithoidiemnay" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanhtien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="chietkhau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_ck_dvsp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tongsauchietkhau" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nguoichot_dvsp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phantram_chotsale_dvsp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_chotsale_dvsp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nguoilam_dichvu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phantram_lamdichvu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_lamdichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="kyhieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tennguoichot_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tennguoilam_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhanh_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="danhgia_nhanvien_lamdichvu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="danhgia_5sao_dv" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="solo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_thedichvu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_hienthi_khidung_thedv" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_hoadon_table" Member="bspa_hoadon_tables">
    <Type Name="bspa_hoadon_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tongtien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="chietkhau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_ck_hoadon" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tongsauchietkhau" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tenkhachhang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotien_dathanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thanhtoan_tienmat" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thanhtoan_chuyenkhoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thanhtoan_quetthe" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sotien_conlai" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="album" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dichvu_hay_sanpham" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sl_dichvu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sl_sanpham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ds_dichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ds_sanpham" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sauck_dichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sauck_sanpham" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="km1_ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_guide" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="nguongoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_lichsu_thanhtoan_table" Member="bspa_lichsu_thanhtoan_tables">
    <Type Name="bspa_lichsu_thanhtoan_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_hoadon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhthuc_thanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotienthanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thoigian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoithanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_nhomthuchi_table" Member="bspa_nhomthuchi_tables">
    <Type Name="bspa_nhomthuchi_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tennhom" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bspa_thuchi_table" Member="bspa_thuchi_tables">
    <Type Name="bspa_thuchi_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nhomthuchi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nguoilapphieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thuchi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nguoinhantien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="duyet_phieuchi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="chophep_duyetvahuy_phieuchi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="nguoihuy_duyet_phieuchi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thoigian_huyduyet_phieuchi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.chinhanh_table" Member="chinhanh_tables">
    <Type Name="chinhanh_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="taikhoan_quantri" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="logo_footer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slogan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="logo_hoadon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.config_baotri_table" Member="config_baotri_tables">
    <Type Name="config_baotri_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="baotri_trangthai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="baotri_thoigian_batdau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="baotri_thoigian_ketthuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.config_lienket_chiase_table" Member="config_lienket_chiase_tables">
    <Type Name="config_lienket_chiase_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.config_nhungma_table" Member="config_nhungma_tables">
    <Type Name="config_nhungma_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nhungma_head" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nhungma_body1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nhungma_body2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nhungma_fanpage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nhungma_googlemaps" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.config_social_media_table" Member="config_social_media_tables">
    <Type Name="config_social_media_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="facebook" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="zalo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="youtube" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="instagram" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="twitter" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tiktok" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="wechat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="linkedin" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="whatsapp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.config_thongtin_table" Member="config_thongtin_tables">
    <Type Name="config_thongtin_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="apple_touch_icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="logo1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tencongty" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slogan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="link_googlemap" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hotline" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="zalo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="logo_in_hoadon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.danhsach_vattu_table" Member="danhsach_vattu_tables">
    <Type Name="danhsach_vattu_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenvattu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nhom" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="donvitinh_sp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="giaban" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="gianhap" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tinhtrang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="vitriphongban" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ncc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.data_yeucau_tuvan_table" Member="data_yeucau_tuvan_tables">
    <Type Name="data_yeucau_tuvan_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="noidung1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="noidung2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="noidung3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="noidung4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.donnhap_vattu_chitiet_table" Member="donnhap_vattu_chitiet_tables">
    <Type Name="donnhap_vattu_chitiet_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_hoadon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_dvsp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_dvsp_taithoidiemnay" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_dvsp_taithoidiemnay" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanhtien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="chietkhau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_ck_dvsp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tongsauchietkhau" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nguoichot_dvsp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phantram_chotsale_dvsp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_chotsale_dvsp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nguoilam_dichvu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phantram_lamdichvu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_lamdichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="kyhieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tennguoichot_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tennguoilam_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhanh_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="danhgia_nhanvien_lamdichvu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="danhgia_5sao_dv" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nsx" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hsd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="solo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sl_daban" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sl_conlai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dvt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.donnhap_vattu_lichsu_thanhtoan_table" Member="donnhap_vattu_lichsu_thanhtoan_tables">
    <Type Name="donnhap_vattu_lichsu_thanhtoan_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_hoadon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhthuc_thanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotienthanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thoigian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoithanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.donnhap_vattu_table" Member="donnhap_vattu_tables">
    <Type Name="donnhap_vattu_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tongtien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="chietkhau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_ck_hoadon" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tongsauchietkhau" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tenkhachhang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotien_dathanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thanhtoan_tienmat" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thanhtoan_chuyenkhoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thanhtoan_quetthe" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sotien_conlai" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="album" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dichvu_hay_sanpham" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sl_dichvu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sl_sanpham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ds_dichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ds_sanpham" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sauck_dichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sauck_sanpham" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="km1_ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_guide" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="nguongoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nhacungcap" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.donnhaphang_chitiet_table" Member="donnhaphang_chitiet_tables">
    <Type Name="donnhaphang_chitiet_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_hoadon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_dvsp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_dvsp_taithoidiemnay" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_dvsp_taithoidiemnay" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanhtien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="chietkhau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_ck_dvsp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tongsauchietkhau" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nguoichot_dvsp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phantram_chotsale_dvsp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_chotsale_dvsp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nguoilam_dichvu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phantram_lamdichvu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_lamdichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="kyhieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tennguoichot_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tennguoilam_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhanh_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="danhgia_nhanvien_lamdichvu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="danhgia_5sao_dv" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nsx" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hsd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="solo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sl_daban" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sl_conlai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dvt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.donnhaphang_lichsu_thanhtoan_table" Member="donnhaphang_lichsu_thanhtoan_tables">
    <Type Name="donnhaphang_lichsu_thanhtoan_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_hoadon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhthuc_thanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotienthanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thoigian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoithanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.donnhaphang_table" Member="donnhaphang_tables">
    <Type Name="donnhaphang_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tongtien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="chietkhau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_ck_hoadon" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tongsauchietkhau" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tenkhachhang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotien_dathanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thanhtoan_tienmat" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thanhtoan_chuyenkhoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thanhtoan_quetthe" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sotien_conlai" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="album" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dichvu_hay_sanpham" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sl_dichvu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sl_sanpham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ds_dichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ds_sanpham" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sauck_dichvu" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sauck_sanpham" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="km1_ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_guide" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="nguongoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nhacungcap" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.donthuoc_khachhang_table" Member="donthuoc_khachhang_tables">
    <Type Name="donthuoc_khachhang_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ngaytaikham" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="noitaikham" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="loidanbacsi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ghichu_khachhang_table" Member="ghichu_khachhang_tables">
    <Type Name="ghichu_khachhang_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.giangvien_table" Member="giangvien_tables">
    <Type Name="giangvien_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hoten_khongdau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="anhdaidien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dienthoai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="zalo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="facebook" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="chuyenmon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sobuoi_lythuyet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sobuoi_thuchanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sobuoi_trogiang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="goidaotao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="danhgiagiangvien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="trangthai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.hethong_checkall_table" Member="hethong_checkall_tables">
    <Type Name="hethong_checkall_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="update_chiphi_codinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.hinhanh_truocsau_khachhang_table" Member="hinhanh_truocsau_khachhang_tables">
    <Type Name="hinhanh_truocsau_khachhang_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hinhanh_truoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhanh_sau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.hocvien_lichsu_thanhtoan_table" Member="hocvien_lichsu_thanhtoan_tables">
    <Type Name="hocvien_lichsu_thanhtoan_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_hocvien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhthuc_thanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotienthanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thoigian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoithanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.hocvien_table" Member="hocvien_tables">
    <Type Name="hocvien_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_giangvien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tengiangvien_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nganhhoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sobuoi_lythuyet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sobuoi_thuchanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sobuoi_trogiang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="goidaotao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hocphi" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="xeploai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaycapbang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="capbang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotien_dathanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sotien_conlai" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hoten_khongdau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="anhdaidien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dienthoai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="zalo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="facebook" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="anh_capbang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.khachhang_table_2023" Member="khachhang_table_2023s">
    <Type Name="khachhang_table_2023">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenkhachhang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hoten_khongdau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="anhdaidien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="magioithieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nguoichamsoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nhomkhachhang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="trangthai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="zalo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="facebook" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hansudung" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="makhoiphuc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hsd_makhoiphuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="permission" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.lichsudiem_table" Member="lichsudiem_tables">
    <Type Name="lichsudiem_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="taikhoan_nhan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="taikhoan_gui" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="loaidiem" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sodiem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tanggiam" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.listbank_table" Member="listbank_tables">
    <Type Name="listbank_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_parent" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_level" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mailbox_table" Member="mailbox_tables">
    <Type Name="mailbox_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thoigian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="daxem" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="nguongoc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.nganh_table" Member="nganh_tables">
    <Type Name="nganh_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.nhacungcap_nhaphang_table" Member="nhacungcap_nhaphang_tables">
    <Type Name="nhacungcap_nhaphang_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.nhomkhachhang_table" Member="nhomkhachhang_tables">
    <Type Name="nhomkhachhang_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tennhom" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.nhomvattu_table" Member="nhomvattu_tables">
    <Type Name="nhomvattu_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tennhom" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.phongban_table" Member="phongban_tables">
    <Type Name="phongban_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.taikhoan_table_2023" Member="taikhoan_table_2023s">
    <Type Name="taikhoan_table_2023">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hoten_khongdau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="anhdaidien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="trangthai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dienthoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zalo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="facebook" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hansudung" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="makhoiphuc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hsd_makhoiphuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="permission" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="luongcoban" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="songaycong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="luongngay" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_bophan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.thedichvu_lichsu_thanhtoan_table" Member="thedichvu_lichsu_thanhtoan_tables">
    <Type Name="thedichvu_lichsu_thanhtoan_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_hoadon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hinhthuc_thanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotienthanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="thoigian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoithanhtoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.thedichvu_table" Member="thedichvu_tables">
    <Type Name="thedichvu_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tenthe" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tenkh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="iddv" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ten_taithoidiemnay" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hsd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tongsoluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sl_dalam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sl_conlai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tongtien" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="chietkhau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_ck_hoadon" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tongsauchietkhau" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sotien_dathanhtoan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sotien_conlai" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nguoichotsale" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phantram_chotsale" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tongtien_chotsale_dvsp" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="tennguoichot_hientai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_nganh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.thongbao_table" Member="thongbao_tables">
    <Type Name="thongbao_table">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nguoithongbao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nguoinhan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thoigian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="daxem" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tinhthanh_table" Member="tinhthanh_tables">
    <Type Name="tinhthanh_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tinhthanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.web_menu_table" Member="web_menu_tables">
    <Type Name="web_menu_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name_en" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="rank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="url_other" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ngaytao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="phanloai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_chinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.web_module_slider_table" Member="web_module_slider_tables">
    <Type Name="web_module_slider_table">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="img" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="but_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rank" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>
