using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Text.RegularExpressions;

public static class SocialLinkIcon_cl
{
    private const string GoogleFaviconTemplate = "https://www.google.com/s2/favicons?sz=128&domain={0}";

    private static readonly Regex MetaTagRegex = new Regex("<meta\\b[^>]*>", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex LinkTagRegex = new Regex("<link\\b[^>]*>", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex AttrRegex = new Regex("(?<name>[a-zA-Z0-9:_-]+)\\s*=\\s*([\\\"'])(?<value>.*?)\\2", RegexOptions.IgnoreCase | RegexOptions.Compiled);

    public static string ResolveIconForSave(string link, string submittedIcon, string existingIcon)
    {
        string linkSafe = NormalizeExternalLink(link);
        string submitted = NormalizeIconValue(submittedIcon);
        string existing = NormalizeIconValue(existingIcon);

        if (!string.IsNullOrEmpty(submitted))
        {
            if (!string.IsNullOrEmpty(existing)
                && string.Equals(submitted, existing, StringComparison.OrdinalIgnoreCase)
                && IsAutoGeneratedIcon(existing))
            {
                string refreshed = ResolveAutoIcon(linkSafe);
                if (!string.IsNullOrEmpty(refreshed))
                    return refreshed;
            }
            return submitted;
        }

        string autoIcon = ResolveAutoIcon(linkSafe);
        if (!string.IsNullOrEmpty(autoIcon))
            return autoIcon;

        return "";
    }

    public static string ResolveIconForDisplay(string icon, string link)
    {
        string explicitIcon = NormalizeIconValue(icon);
        if (!string.IsNullOrEmpty(explicitIcon))
            return explicitIcon;

        return ResolveFastFallbackIcon(link);
    }

    public static bool IsAutoGeneratedIcon(string icon)
    {
        string value = (icon ?? "").Trim();
        if (value.Length == 0)
            return false;

        if (value.StartsWith("https://www.google.com/s2/favicons", StringComparison.OrdinalIgnoreCase))
            return true;

        if (value.StartsWith("https://s2.googleusercontent.com/s2/favicons", StringComparison.OrdinalIgnoreCase))
            return true;

        return false;
    }

    public static string NormalizeExternalLink(string link)
    {
        string raw = (link ?? "").Trim();
        if (raw.Length == 0)
            return "";
        if (raw.StartsWith("javascript:", StringComparison.OrdinalIgnoreCase))
            return "";

        Uri absolute;
        if (!Uri.TryCreate(raw, UriKind.Absolute, out absolute))
        {
            string normalized = "https://" + raw.TrimStart('/');
            if (!Uri.TryCreate(normalized, UriKind.Absolute, out absolute))
                return "";
        }

        if (!string.Equals(absolute.Scheme, Uri.UriSchemeHttp, StringComparison.OrdinalIgnoreCase)
            && !string.Equals(absolute.Scheme, Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase))
            return "";

        return absolute.AbsoluteUri;
    }

    private static string ResolveAutoIcon(string normalizedLink)
    {
        if (string.IsNullOrEmpty(normalizedLink))
            return "";

        string preset = ResolveKnownBrandIcon(normalizedLink);
        if (!string.IsNullOrEmpty(preset))
            return preset;

        string fromMeta = TryResolveIconFromPageMeta(normalizedLink);
        if (!string.IsNullOrEmpty(fromMeta))
            return fromMeta;

        return ResolveGoogleFavicon(normalizedLink);
    }

    private static string ResolveFastFallbackIcon(string link)
    {
        string normalizedLink = NormalizeExternalLink(link);
        if (string.IsNullOrEmpty(normalizedLink))
            return "";

        string preset = ResolveKnownBrandIcon(normalizedLink);
        if (!string.IsNullOrEmpty(preset))
            return preset;

        return ResolveGoogleFavicon(normalizedLink);
    }

    private static string ResolveGoogleFavicon(string normalizedLink)
    {
        Uri uri;
        if (!Uri.TryCreate(normalizedLink, UriKind.Absolute, out uri))
            return "";
        if (string.IsNullOrEmpty(uri.Host))
            return "";

        return string.Format(GoogleFaviconTemplate, Uri.EscapeDataString(uri.Host));
    }

    private static string ResolveKnownBrandIcon(string normalizedLink)
    {
        Uri uri;
        if (!Uri.TryCreate(normalizedLink, UriKind.Absolute, out uri))
            return "";

        string host = (uri.Host ?? "").Trim().ToLowerInvariant();
        if (host.Length == 0)
            return "";

        if (host.Contains("facebook.com") || host == "fb.com" || host.EndsWith(".fb.com"))
            return "/uploads/images/icon/icon-fb.png";
        if (host.Contains("zalo.me") || host.Contains("zalo.vn") || host.Contains("chat.zalo"))
            return "/uploads/images/icon/icon-zalo.png";
        if (host.Contains("tiktok.com") || host == "vt.tiktok.com")
            return "/uploads/images/icon/icon-tiktok.png";
        if (host.Contains("youtube.com") || host == "youtu.be")
            return "/uploads/images/icon/icon-youtube.png";
        if (host.Contains("instagram.com"))
            return "/uploads/images/icon/ins.png";
        if (host.Contains("linkedin.com"))
            return "/uploads/images/icon/linkedIn.png";
        if (host.Contains("twitter.com") || host == "x.com" || host.EndsWith(".x.com"))
            return "/uploads/images/icon/twitter.png";
        if (host.Contains("whatsapp.com") || host == "wa.me")
            return "/uploads/images/icon/WhatsApp.png";
        if (host.Contains("wechat.com") || host.Contains("weixin.qq.com"))
            return "/uploads/images/icon/wechat.png";

        return "";
    }

    private static string TryResolveIconFromPageMeta(string normalizedLink)
    {
        try
        {
            Uri pageUri;
            if (!Uri.TryCreate(normalizedLink, UriKind.Absolute, out pageUri))
                return "";

            if (IsUnsafeHostForServerFetch(pageUri.Host))
                return "";

            string html = DownloadHtml(pageUri);
            if (string.IsNullOrEmpty(html))
                return "";

            string icon = FindOpenGraphImage(pageUri, html);
            if (!string.IsNullOrEmpty(icon))
                return icon;

            icon = FindAppleTouchIcon(pageUri, html);
            if (!string.IsNullOrEmpty(icon))
                return icon;

            icon = FindGenericFavicon(pageUri, html);
            if (!string.IsNullOrEmpty(icon))
                return icon;
        }
        catch
        {
        }

        return "";
    }

    private static string DownloadHtml(Uri pageUri)
    {
        HttpWebRequest req = (HttpWebRequest)WebRequest.Create(pageUri);
        req.Method = "GET";
        req.Timeout = 3500;
        req.ReadWriteTimeout = 3500;
        req.UserAgent = "Mozilla/5.0 (compatible; AhaSaleBot/1.0; +https://ahasale.vn)";
        req.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
        req.AllowAutoRedirect = true;
        req.MaximumAutomaticRedirections = 5;
        req.Accept = "text/html,application/xhtml+xml";

        using (HttpWebResponse res = (HttpWebResponse)req.GetResponse())
        {
            string contentType = (res.ContentType ?? "").ToLowerInvariant();
            if (contentType.Length > 0
                && !contentType.Contains("text/html")
                && !contentType.Contains("application/xhtml"))
                return "";

            using (Stream stream = res.GetResponseStream())
            {
                if (stream == null)
                    return "";

                using (StreamReader reader = new StreamReader(stream))
                {
                    string html = reader.ReadToEnd();
                    if (html == null)
                        return "";
                    if (html.Length > 350000)
                        html = html.Substring(0, 350000);
                    return html;
                }
            }
        }
    }

    private static string FindOpenGraphImage(Uri pageUri, string html)
    {
        MatchCollection matches = MetaTagRegex.Matches(html ?? "");
        foreach (Match m in matches)
        {
            string tag = m.Value;
            string property = GetAttribute(tag, "property").ToLowerInvariant();
            string name = GetAttribute(tag, "name").ToLowerInvariant();
            bool isOgImage = property == "og:image" || name == "og:image";
            if (!isOgImage)
                continue;

            string content = GetAttribute(tag, "content");
            string resolved = ResolvePossiblyRelativeUrl(pageUri, content);
            if (!string.IsNullOrEmpty(resolved))
                return resolved;
        }
        return "";
    }

    private static string FindAppleTouchIcon(Uri pageUri, string html)
    {
        MatchCollection matches = LinkTagRegex.Matches(html ?? "");
        foreach (Match m in matches)
        {
            string tag = m.Value;
            string rel = GetAttribute(tag, "rel").ToLowerInvariant();
            if (string.IsNullOrEmpty(rel))
                continue;

            if (!rel.Contains("apple-touch-icon"))
                continue;

            string href = GetAttribute(tag, "href");
            string resolved = ResolvePossiblyRelativeUrl(pageUri, href);
            if (!string.IsNullOrEmpty(resolved))
                return resolved;
        }
        return "";
    }

    private static string FindGenericFavicon(Uri pageUri, string html)
    {
        MatchCollection matches = LinkTagRegex.Matches(html ?? "");
        foreach (Match m in matches)
        {
            string tag = m.Value;
            string rel = GetAttribute(tag, "rel").ToLowerInvariant();
            if (string.IsNullOrEmpty(rel))
                continue;

            if (!rel.Contains("icon"))
                continue;

            string href = GetAttribute(tag, "href");
            string resolved = ResolvePossiblyRelativeUrl(pageUri, href);
            if (!string.IsNullOrEmpty(resolved))
                return resolved;
        }

        string fallback = ResolvePossiblyRelativeUrl(pageUri, "/favicon.ico");
        return fallback;
    }

    private static string GetAttribute(string tag, string attrName)
    {
        if (string.IsNullOrEmpty(tag) || string.IsNullOrEmpty(attrName))
            return "";

        MatchCollection matches = AttrRegex.Matches(tag);
        foreach (Match match in matches)
        {
            string name = (match.Groups["name"].Value ?? "").Trim();
            if (!string.Equals(name, attrName, StringComparison.OrdinalIgnoreCase))
                continue;
            return (match.Groups["value"].Value ?? "").Trim();
        }
        return "";
    }

    private static string ResolvePossiblyRelativeUrl(Uri pageUri, string rawUrl)
    {
        string candidate = (rawUrl ?? "").Trim();
        if (candidate.Length == 0)
            return "";
        if (candidate.StartsWith("javascript:", StringComparison.OrdinalIgnoreCase))
            return "";

        if (candidate.StartsWith("//", StringComparison.Ordinal))
            candidate = pageUri.Scheme + ":" + candidate;

        Uri absolute;
        if (Uri.TryCreate(candidate, UriKind.Absolute, out absolute))
        {
            if (absolute.Scheme == Uri.UriSchemeHttp || absolute.Scheme == Uri.UriSchemeHttps)
                return absolute.AbsoluteUri;
            return "";
        }

        if (Uri.TryCreate(pageUri, candidate, out absolute))
        {
            if (absolute.Scheme == Uri.UriSchemeHttp || absolute.Scheme == Uri.UriSchemeHttps)
                return absolute.AbsoluteUri;
        }

        return "";
    }

    private static string NormalizeIconValue(string icon)
    {
        return NormalizeIconValue((object)icon);
    }

    private static string NormalizeIconValue(object icon)
    {
        string image = (icon ?? "").ToString().Trim();
        if (string.IsNullOrEmpty(image))
            return "";
        if (image.StartsWith("javascript:", StringComparison.OrdinalIgnoreCase))
            return "";

        Uri absolute;
        if (Uri.TryCreate(image, UriKind.Absolute, out absolute))
        {
            if (absolute.Scheme == Uri.UriSchemeHttp || absolute.Scheme == Uri.UriSchemeHttps)
                return absolute.AbsoluteUri;
            return "";
        }

        if (image.StartsWith("~/", StringComparison.Ordinal))
            image = image.Substring(1);
        if (!image.StartsWith("/", StringComparison.Ordinal))
            image = "/" + image.TrimStart('/');

        return image;
    }

    private static bool IsUnsafeHostForServerFetch(string host)
    {
        string value = (host ?? "").Trim().ToLowerInvariant();
        if (value.Length == 0)
            return true;
        if (value == "localhost")
            return true;

        IPAddress ip;
        if (!IPAddress.TryParse(value, out ip))
            return false;

        if (IPAddress.IsLoopback(ip))
            return true;

        if (ip.AddressFamily == AddressFamily.InterNetwork)
        {
            byte[] b = ip.GetAddressBytes();
            if (b[0] == 10) return true;
            if (b[0] == 127) return true;
            if (b[0] == 192 && b[1] == 168) return true;
            if (b[0] == 172 && b[1] >= 16 && b[1] <= 31) return true;
            if (b[0] == 169 && b[1] == 254) return true;
        }

        if (ip.AddressFamily == AddressFamily.InterNetworkV6)
        {
            if (ip.IsIPv6LinkLocal || ip.IsIPv6Multicast || ip.IsIPv6SiteLocal)
                return true;
        }

        return false;
    }
}
