server {
    listen 80 default_server;
    server_name localhost 127.0.0.1;

    root /app;
    index Default.aspx default.aspx index.html;

    location = / {
        return 302 /admin/login.aspx;
    }

    location / {
        try_files $uri $uri/ @mono;
    }

    location ~* \.(aspx|ashx)$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
        fastcgi_param PATH_INFO "";
        fastcgi_param APPL_PHYSICAL_PATH /app;
        fastcgi_param APPL_MD_PATH /;
        fastcgi_param DOCUMENT_ROOT /app;
        fastcgi_param SERVER_NAME $host;
        fastcgi_pass unix:/run/mono/fastcgi.sock;
    }

    location @mono {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param APPL_PHYSICAL_PATH /app;
        fastcgi_param APPL_MD_PATH /;
        fastcgi_param DOCUMENT_ROOT /app;
        fastcgi_param SERVER_NAME $host;
        fastcgi_pass unix:/run/mono/fastcgi.sock;
    }
}
