#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
source "$ROOT_DIR/scripts/lib/local-db-env.sh"
aha_export_local_db_env

BASE_URL="${BASE_URL:-https://ahasale.local}"
ADMIN_USER="${ADMIN_USER:-admin}"
ADMIN_PASS="${ADMIN_PASS:-123456}"
SERVICE_NAME="${SERVICE_NAME:-runtime_service_$(date +%s)}"
PRODUCT_NAME="${PRODUCT_NAME:-runtime_product_$(date +%s)}"
RUNTIME_USER_ACCOUNT="${RUNTIME_USER_ACCOUNT:-rtu$(date +%s)}"
RUNTIME_VATTU_NAME="${RUNTIME_VATTU_NAME:-runtime_vattu_$(date +%s)}"
PHONE_SEED="$(printf '%08d' "$(( $(date +%s) % 100000000 ))")"
RUNTIME_CUSTOMER_NAME="${RUNTIME_CUSTOMER_NAME:-Runtime Customer ${PHONE_SEED#${PHONE_SEED%????}}}"
RUNTIME_CUSTOMER_PHONE="${RUNTIME_CUSTOMER_PHONE:-09${PHONE_SEED}}"
RUNTIME_APPOINTMENT_NOTE="${RUNTIME_APPOINTMENT_NOTE:-Runtime appointment ${RUNTIME_CUSTOMER_PHONE}}"
RUNTIME_INVOICE_CUSTOMER_NAME="${RUNTIME_INVOICE_CUSTOMER_NAME:-Runtime Invoice ${PHONE_SEED#${PHONE_SEED%????}}}"
RUNTIME_INVOICE_PHONE="${RUNTIME_INVOICE_PHONE:-08${PHONE_SEED}}"
RUNTIME_IMPORT_NOTE="${RUNTIME_IMPORT_NOTE:-Runtime import ${PRODUCT_NAME}}"
RUNTIME_INCLUDE_INVOICE_DETAIL="${RUNTIME_INCLUDE_INVOICE_DETAIL:-0}"
RUNTIME_INCLUDE_WAREHOUSE="${RUNTIME_INCLUDE_WAREHOUSE:-0}"
RUNTIME_INCLUDE_SERVICE_CARD="${RUNTIME_INCLUDE_SERVICE_CARD:-0}"
RUNTIME_INCLUDE_STUDENT="${RUNTIME_INCLUDE_STUDENT:-0}"
RUNTIME_INCLUDE_SUPPLY_IMPORT="${RUNTIME_INCLUDE_SUPPLY_IMPORT:-0}"
RUNTIME_ENABLE_SQL_VALIDATION="${RUNTIME_ENABLE_SQL_VALIDATION:-0}"
PLAYWRIGHT_WORKDIR="${PLAYWRIGHT_WORKDIR:-/tmp/ahasale-pw}"
PLAYWRIGHT_MODULE_PATH="${PLAYWRIGHT_MODULE_PATH:-${PLAYWRIGHT_WORKDIR}/node_modules/playwright}"

export BASE_URL ADMIN_USER ADMIN_PASS SERVICE_NAME PRODUCT_NAME \
  RUNTIME_USER_ACCOUNT RUNTIME_VATTU_NAME \
  RUNTIME_CUSTOMER_NAME RUNTIME_CUSTOMER_PHONE RUNTIME_APPOINTMENT_NOTE \
  RUNTIME_INVOICE_CUSTOMER_NAME RUNTIME_INVOICE_PHONE RUNTIME_IMPORT_NOTE \
  RUNTIME_INCLUDE_INVOICE_DETAIL RUNTIME_INCLUDE_WAREHOUSE \
  RUNTIME_INCLUDE_SERVICE_CARD RUNTIME_INCLUDE_STUDENT RUNTIME_INCLUDE_SUPPLY_IMPORT \
  RUNTIME_ENABLE_SQL_VALIDATION \
  PLAYWRIGHT_WORKDIR PLAYWRIGHT_MODULE_PATH

printf "Running authenticated AhaShine admin runtime test at %s\n" "$BASE_URL"
printf "SERVICE_NAME=%s\n" "$SERVICE_NAME"
printf "PRODUCT_NAME=%s\n" "$PRODUCT_NAME"
printf "RUNTIME_USER_ACCOUNT=%s\n" "$RUNTIME_USER_ACCOUNT"
printf "RUNTIME_VATTU_NAME=%s\n" "$RUNTIME_VATTU_NAME"
printf "RUNTIME_CUSTOMER_NAME=%s\n" "$RUNTIME_CUSTOMER_NAME"
printf "RUNTIME_CUSTOMER_PHONE=%s\n" "$RUNTIME_CUSTOMER_PHONE"
printf "RUNTIME_APPOINTMENT_NOTE=%s\n" "$RUNTIME_APPOINTMENT_NOTE"
printf "RUNTIME_INVOICE_CUSTOMER_NAME=%s\n" "$RUNTIME_INVOICE_CUSTOMER_NAME"
printf "RUNTIME_INVOICE_PHONE=%s\n" "$RUNTIME_INVOICE_PHONE"
printf "RUNTIME_IMPORT_NOTE=%s\n" "$RUNTIME_IMPORT_NOTE"
printf "RUNTIME_INCLUDE_INVOICE_DETAIL=%s\n" "$RUNTIME_INCLUDE_INVOICE_DETAIL"
printf "RUNTIME_INCLUDE_WAREHOUSE=%s\n" "$RUNTIME_INCLUDE_WAREHOUSE"
printf "RUNTIME_INCLUDE_SERVICE_CARD=%s\n" "$RUNTIME_INCLUDE_SERVICE_CARD"
printf "RUNTIME_INCLUDE_STUDENT=%s\n" "$RUNTIME_INCLUDE_STUDENT"
printf "RUNTIME_INCLUDE_SUPPLY_IMPORT=%s\n" "$RUNTIME_INCLUDE_SUPPLY_IMPORT"
printf "RUNTIME_ENABLE_SQL_VALIDATION=%s\n" "$RUNTIME_ENABLE_SQL_VALIDATION"

ensure_playwright() {
  if [ -f "$PLAYWRIGHT_MODULE_PATH/index.js" ]; then
    return
  fi

  mkdir -p "$PLAYWRIGHT_WORKDIR"
  (
    cd "$PLAYWRIGHT_WORKDIR"
    if [ ! -f package.json ]; then
      npm init -y >/dev/null
    fi
    npm install @playwright/test >/dev/null
  )
}

run_sql_validation() {
  local sql_path_in_container="/tmp/test-gianhang-admin-runtime.sql"
  docker cp scripts/sql/test-gianhang-admin-runtime.sql "${DB_CONTAINER}:${sql_path_in_container}" >/dev/null
  docker exec "$DB_CONTAINER" /opt/mssql-tools18/bin/sqlcmd \
    -b -C -S localhost -U sa -P 'AhaSaleLocal#2026' -l "$DB_LOGIN_TIMEOUT" -t "$DB_QUERY_TIMEOUT" -d "$LOCAL_DB_NAME" \
    -v SERVICE_NAME="$SERVICE_NAME" -v PRODUCT_NAME="$PRODUCT_NAME" \
    -v RUNTIME_USER_ACCOUNT="$RUNTIME_USER_ACCOUNT" -v RUNTIME_VATTU_NAME="$RUNTIME_VATTU_NAME" \
    -v RUNTIME_CUSTOMER_NAME="$RUNTIME_CUSTOMER_NAME" -v RUNTIME_CUSTOMER_PHONE="$RUNTIME_CUSTOMER_PHONE" \
    -v RUNTIME_APPOINTMENT_NOTE="$RUNTIME_APPOINTMENT_NOTE" \
    -v RUNTIME_INVOICE_CUSTOMER_NAME="$RUNTIME_INVOICE_CUSTOMER_NAME" -v RUNTIME_INVOICE_PHONE="$RUNTIME_INVOICE_PHONE" \
    -v RUNTIME_IMPORT_NOTE="$RUNTIME_IMPORT_NOTE" -v RUNTIME_INCLUDE_INVOICE_DETAIL="$RUNTIME_INCLUDE_INVOICE_DETAIL" \
    -v RUNTIME_INCLUDE_WAREHOUSE="$RUNTIME_INCLUDE_WAREHOUSE" \
    -i "$sql_path_in_container"
}

if [ "$RUNTIME_INCLUDE_INVOICE_DETAIL" = "1" ] || [ "$RUNTIME_INCLUDE_WAREHOUSE" = "1" ] || [ "$RUNTIME_INCLUDE_SERVICE_CARD" = "1" ] || [ "$RUNTIME_INCLUDE_STUDENT" = "1" ] || [ "$RUNTIME_INCLUDE_SUPPLY_IMPORT" = "1" ]; then
  ensure_playwright

  DEEP_INCLUDE_INVOICE_DETAIL="$RUNTIME_INCLUDE_INVOICE_DETAIL"
  DEEP_INCLUDE_WAREHOUSE="$RUNTIME_INCLUDE_WAREHOUSE"
  DEEP_INCLUDE_SERVICE_CARD="$RUNTIME_INCLUDE_SERVICE_CARD"
  DEEP_INCLUDE_STUDENT="$RUNTIME_INCLUDE_STUDENT"
  DEEP_INCLUDE_SUPPLY_IMPORT="$RUNTIME_INCLUDE_SUPPLY_IMPORT"
  RUNTIME_JSON_FILE="$(mktemp /tmp/gianhang-admin-runtime-deep.XXXXXX.json)"
  trap 'rm -f "$RUNTIME_JSON_FILE"' EXIT

  export RUNTIME_OUTPUT_JSON_PATH="$RUNTIME_JSON_FILE"
  export RUNTIME_CREATE_ONLY=1
  export RUNTIME_INCLUDE_INVOICE_DETAIL=0
  export RUNTIME_INCLUDE_WAREHOUSE=0
  export RUNTIME_INCLUDE_SERVICE_CARD=0
  export RUNTIME_INCLUDE_STUDENT=0
  export RUNTIME_INCLUDE_SUPPLY_IMPORT=0
  python3 -u scripts/test-gianhang-admin-runtime.py

  eval "$(
    python3 - "$RUNTIME_JSON_FILE" <<'PY'
import json
import shlex
import sys

with open(sys.argv[1], "r", encoding="utf-8") as handle:
    data = json.load(handle)

for key, value in data.items():
    print(f'export {key}={shlex.quote(str(value))}')
PY
  )"

  export RUNTIME_OUTPUT_JSON_PATH=""
  export RUNTIME_CREATE_ONLY=0
  export RUNTIME_INCLUDE_INVOICE_DETAIL="$DEEP_INCLUDE_INVOICE_DETAIL"
  export RUNTIME_INCLUDE_WAREHOUSE="$DEEP_INCLUDE_WAREHOUSE"
  export RUNTIME_INCLUDE_SERVICE_CARD="$DEEP_INCLUDE_SERVICE_CARD"
  export RUNTIME_INCLUDE_STUDENT="$DEEP_INCLUDE_STUDENT"
  export RUNTIME_INCLUDE_SUPPLY_IMPORT="$DEEP_INCLUDE_SUPPLY_IMPORT"
  node scripts/playwright/gianhang-admin-deep.js
else
  python3 -u scripts/test-gianhang-admin-runtime.py
fi

if [ "$RUNTIME_ENABLE_SQL_VALIDATION" = "1" ]; then
  run_sql_validation
else
  echo "Skipped SQL validation (set RUNTIME_ENABLE_SQL_VALIDATION=1 to enable)."
fi

echo "AhaShine admin runtime test passed."
